title: I'm a cloud architect 
email: alan.bellon.00@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  As a Cloud Architect with a Computer Science background, I’m passionate about scalable solutions and programming. I love using Neovim (nvim), exploring philosophy, and running in my free time. Follow my blog for insights on cloud computing, coding, and personal growth.


baseurl: "" # the subpath of your site, e.g. /blog
url: "" #123porAlan.github.io # the base hostname & protocol for your site, e.g. http://example.com


twitter_username: jekyllrb
github_username:  jek123porAlan

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
